"""
AUTO-GENERATED BY AUTO-CODEX (MOCK MODE)

Intent:
Build a simple Python calculator
"""

def add(a, b):
    """Return the sum of two numbers"""
    return a + b

def subtract(a, b):
    """Return the difference of two numbers"""
    return a - b

def multiply(a, b):
    """Return the product of two numbers"""
    return a * b

def divide(a, b):
    """Return the division of two numbers"""
    if b == 0:
        return "Error: Division by zero"
    return a / b

if __name__ == "__main__":
    print("Calculator Demo")
    print("Add:", add(10, 5))
    print("Subtract:", subtract(10, 5))
    print("Multiply:", multiply(10, 5))
    print("Divide:", divide(10, 5))
