import os
from pathlib import Path

print("🚀 AUTO-CODEX generator started")

# Read intent
intent_path = Path("intent/idea.md")
if not intent_path.exists():
    raise FileNotFoundError("intent/idea.md not found")

intent = intent_path.read_text().strip()
if not intent:
    raise ValueError("intent/idea.md is empty")

print("✅ Intent loaded")

# Decide mode
USE_MOCK = os.getenv("MOCK_MODE", "true").lower() == "true"
API_KEY = os.getenv("OPENAI_API_KEY")

# Output directory
output_dir = Path("projects/generated_app")
output_dir.mkdir(parents=True, exist_ok=True)
output_file = output_dir / "app.py"

# ---------------- MOCK MODE ----------------
if USE_MOCK or not API_KEY:
    print("🧪 Running in MOCK MODE (no API used)")

    mock_code = '''"""
AUTO-GENERATED BY AUTO-CODEX (MOCK MODE)

Intent:
Build a simple Python calculator
"""

def add(a, b):
    """Return the sum of two numbers"""
    return a + b

def subtract(a, b):
    """Return the difference of two numbers"""
    return a - b

def multiply(a, b):
    """Return the product of two numbers"""
    return a * b

def divide(a, b):
    """Return the division of two numbers"""
    if b == 0:
        return "Error: Division by zero"
    return a / b

if __name__ == "__main__":
    print("Calculator Demo")
    print("Add:", add(10, 5))
    print("Subtract:", subtract(10, 5))
    print("Multiply:", multiply(10, 5))
    print("Divide:", divide(10, 5))
'''

    output_file.write_text(mock_code, encoding="utf-8")
    print(f"🎉 Mock code generated → {output_file}")

# ---------------- REAL API MODE ----------------
else:
    print("🤖 OpenAI mode enabled (API key detected)")
    from openai import OpenAI

    client = OpenAI(api_key=API_KEY)

    prompt = f"""
You are a senior Python developer.

Generate a clean, beginner-friendly Python program
based strictly on the following intent.

INTENT:
{intent}

RULES:
- Use functions
- Add clear comments
- Output ONLY valid Python code
"""

    response = client.responses.create(
        model="gpt-4.1-mini",
        input=prompt
    )

    code = response.output_text.strip()
    output_file.write_text(code, encoding="utf-8")
    print(f"🎉 AI-generated code written → {output_file}")
